"""add user role

Revision ID: f32a9980d43e
Revises: 23ea56ae759f
Create Date: 2024-10-13 23:22:29.479664

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f32a9980d43e"
down_revision = "23ea56ae759f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("role", sa.Enum("ADMIN", "USER", name="userrole"), nullable=False)
        )
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("role")

    # ### end Alembic commands ###
